<?php

return array (
  'on' => 'on',
  'api' => 
  array (
    'token' => '5d74372a70366539987e5d5044a21d21',
    'domain' => '',
  ),
  'd' => 'kinopushka.org',
  'player' => 
  array (
    'script' => 'https://weblion777.github.io/hdvb_new.js',
  ),
  'xfields' => 
  array (
    'search' => 
    array (
      'kinopoisk_id' => 'kinopoisk_id',
      'world_art_id' => 'world_art_id',
    ),
    'write' => 
    array (
      'source' => 'iframe_hdvb',
      'quality' => 'quality_hdvb',
      'translation' => 'translator_hdvb',
      'season' => 'last_season_hdvb',
      'episode' => 'last_episode_hdvb',
      'year' => '',
      'translations' => '',
      'custom_quality' => '',
      'custom_translation' => '',
      'custom_translations' => '',
      'format_season' => '',
      'format_season_type' => '0',
      'format_episode' => '',
      'format_episode_type' => '0',
    ),
    'npt_update' => '',
  ),
  'seo' => 
  array (
    'url' => '[title_ru]{title_ru}[/title_ru][year] {year}[/year][translation] {translation}[/translation][quality] {quality}[/quality][serial][season] {season} сезон[/season][episode] {episode} серия[/episode][/serial]',
    'title' => '[title_ru]{title_ru}[/title_ru]',
    'meta' => 
    array (
      'title' => '[title_ru]{title_ru}[/title_ru][year] {year}[/year][translation] {translation}[/translation][quality] {quality}[/quality][serial][season] {season} сезон[/season][episode] {episode} серия[/episode][/serial]',
      'description' => '[title_ru]{title_ru}[/title_ru][year] {year}[/year][translation] {translation}[/translation][quality] {quality}[/quality][serial][season] {season} сезон[/season][episode] {episode} серия[/episode][/serial]',
    ),
  ),
  'update' => 
  array (
    'type' => '0',
    'interval' => '3h',
    'serials' => 
    array (
      'on' => 'on',
      'up' => '1',
      'priority' => '',
    ),
  ),
  'serials' => 
  array (
    'updates' => 
    array (
      'days' => '',
      'items' => '',
    ),
  ),
  'custom' => 
  array (
    'qualities' => 
    array (
    ),
    'translations' => 
    array (
    ),
  ),
  'translations' => 
  array (
    1 => '2x2',
    2 => 'Agatha Studdio',
    3 => 'Alexfilm',
    4 => 'AlFair Studio',
    5 => 'Alt Pro',
    6 => 'AMC',
    7 => 'Amedia',
    8 => 'Ancord',
    10 => 'AniLibria',
    11 => 'Animedia',
    12 => 'AvePremier',
    13 => 'AXN Sci-fi',
    14 => 'BaibaKo',
    15 => 'Coldfilm',
    16 => 'СТС',
    17 => 'D1',
    18 => 'datynet',
    19 => 'den904',
    20 => 'Discovery',
    21 => 'Diva Universal',
    22 => 'DreamRecords',
    23 => 'Filiza Studio',
    24 => 'Flux-Team',
    25 => 'FocusStudio',
    26 => 'Fox',
    27 => 'F-TRAIN',
    28 => 'Gears Media',
    29 => 'GladiolusTV',
    30 => 'Good People',
    31 => 'GREEN TEA',
    32 => 'HamsterStudio',
    33 => 'HDrezka Studio',
    34 => 'НТВ',
    35 => 'IdeaFilm',
    36 => 'Jaskier',
    37 => 'Jetvis Studio',
    38 => 'Jimmy J.',
    39 => 'JWA Project',
    40 => 'KANSAI',
    41 => 'Levelin',
    42 => 'Lord32x',
    43 => 'LostFilm',
    44 => 'Lw13pro',
    45 => 'MC Entertainment',
    46 => 'napaBo3uk',
    47 => 'Narkom Pro',
    48 => 'Newstudio',
    49 => 'Nice-Media',
    50 => 'Novafilm',
    51 => 'Novamedia',
    52 => 'OMSKBIRD records',
    53 => 'Onibaku',
    54 => 'Ozz',
    55 => 'Paramount Comedy',
    56 => 'PashaUp',
    57 => 'Prichudiki',
    58 => 'ProjektorShow',
    59 => 'R.A.I.M',
    60 => 'SDI Media',
    61 => 'SET Russia',
    62 => 'SHIZA Project',
    63 => 'Sony Sci-Fi',
    64 => 'Sony Turbo',
    65 => 'STEPonee',
    66 => 'StudioBand',
    67 => 'Sunshine Studio',
    68 => 'To4ka',
    69 => 'Tycoon',
    70 => 'Universal Russia',
    71 => 'Victory-Films',
    72 => 'ViruseProject',
    73 => 'VO-production',
    74 => 'xaros',
    75 => 'xixidok',
    76 => 'Zamez',
    77 => 'АРК ТВ',
    78 => 'Гаврилов',
    79 => 'Гоблин',
    80 => 'Дасевич',
    81 => 'двухголосый закадровый',
    82 => 'Дубляж',
    83 => 'Есарев',
    84 => 'Живов',
    85 => 'Кравец',
    86 => 'Кубик в Кубе',
    87 => 'Кураж-бамбей',
    88 => 'Матвеев',
    89 => 'многоголосый закадровый',
    90 => 'Невафильм',
    91 => 'Несмертельное оружие',
    92 => 'Не требуется',
    93 => 'одноголосый закадровый',
    94 => 'Первый канал',
    95 => 'Сербин',
    96 => 'Студия Райдо',
    97 => 'Субтитры',
    99 => 'Сыендук',
    100 => 'ТВ-3',
    101 => 'Украинский',
    102 => 'Шадинский',
    103 => 'Перевод не требуется',
    104 => 'Дубляж NOIR',
    105 => 'AniDUB',
    106 => 'SoftBox',
    107 => 'Дубляж [Лицензия]',
    108 => 'Дубляж [Звук с TS]',
    109 => 'Дубляж [Чистый звук]',
    110 => 'Профессиональный (многоголосый) [Лицензия]',
    111 => 'KosharaSerials',
    112 => 'АРК-ТВ Studio & VSI International',
    113 => 'Netflix',
    114 => 'Marvel',
    115 => 'Octopus',
    116 => 'Лицензия',
    117 => 'TVShows',
    118 => 'Lucky Production',
    119 => 'Spike',
    120 => 'Zone Vision',
    121 => 'РуФилмс',
    122 => 'BTI Studios',
    123 => 'Кириллица',
    124 => 'Пифагор',
    125 => 'ShowJet',
    126 => 'Профессиональный (многоголосый)',
    127 => 'Fox Life',
    128 => '123',
    129 => 'Contentica',
    130 => 'Wink',
    131 => 'The Kitchen Russia',
    132 => 'IVI',
    133 => 'Мобильное телевидение',
    134 => 'True Dubbing Studio',
    135 => 'Форс Медиа',
    136 => 'ТВЦ',
    137 => 'Eurochannel',
    138 => 'NewStation',
    139 => 'AMS',
    140 => 'Greb&Creative',
    141 => 'GoldTeam',
    142 => 'Футурум',
    143 => 'GreenРай Studio',
    144 => 'МногоТВ',
    145 => 'ДТВ',
    146 => 'Sony',
    147 => 'Русский Репортаж',
    148 => 'DobleRec',
    149 => 'CBS Drama',
    150 => 'ТНТ',
    151 => 'Нота',
    152 => 'DexterTV',
    153 => 'National Geographic',
    154 => 'CLS Media',
    155 => 'Первый ТВЧ',
    156 => 'Пятница',
    158 => 'Храм Дорам ТВ',
    159 => 'Велес',
    160 => 'Игмар',
    161 => 'XDUB DORAMA',
    162 => 'Профессиональный (двухголосый)',
    163 => 'Kiitos',
    164 => 'FireDub',
    165 => 'AnyFilm',
    166 => 'СВ-Дубль',
    167 => 'WestFilm',
    168 => 'HighHopes',
    169 => 'Sound-Group',
    170 => 'Korean Craze',
    171 => 'TrainStudio',
    172 => 'Flarrow Films',
    173 => 'RusFilm',
    174 => 'Телеканал Ю',
    175 => 'DoubleRec',
    176 => 'Force Media',
    177 => 'MTV',
    178 => 'РЕН-ТВ',
    179 => 'Hallmark Russia',
    180 => 'Видеопродакшн',
    181 => 'Кинопоказ',
    182 => 'Инис',
    183 => 'Ultradox',
    184 => 'Fox Crime',
    185 => 'VIP Serial',
    186 => 'Муз-ТВ',
    187 => 'Gramalant',
    188 => 'Project Web Mania',
    189 => 'Хабар',
    190 => 'Crunchyroll',
    191 => 'Культура',
    192 => 'BBC Saint-Petersburg',
    193 => 'Goodtime Media',
    194 => 'СВ Студия',
    195 => 'Intra Communications',
    196 => 'Домашний',
    197 => 'Saint Sound',
    198 => 'ВГТРК',
    199 => 'Эй Би Видео',
    200 => 'KerobTV',
    201 => 'Русский дубляж',
    202 => 'Премьер',
    203 => 'Premier',
    204 => '5 Канал',
    205 => 'Arabian',
    206 => 'Brazilian',
    207 => 'French',
    208 => 'Hindi',
    209 => 'Latino',
    210 => 'Turkish',
    211 => 'English',
    212 => 'Українська',
    213 => 'Қазақша',
  ),
  'cronkey' => '6cc8508242b7fbcaac674e6833b35697',
  'domain' => 'https://vid1684494033.vb17123filippaaniketos.pw/',
  'domain_update' => 1684494033,
);